### ISSUE TITLE
Remeber Me

### ISSUE THREAD

**Issue by knownasilya** [knownasilya/just-auth#10]
So the solution that we came up for this is to have two tokens, with different "tags" and expiration dates.

* login - This is the short term token for handling login
* remember - The long term token, for remember me

**Comment by knownasilya** [comment]
cc @calvinmetcalf for fleshing this out to include what each does and how they work together.

Pros/cons as well maybe.

**Comment by calvinmetcalf** [comment]
they should have different scopes with the remember one always requiring a user lookup in the database

**Comment by knownasilya** [comment]
cc @ismyrnow

**Comment by knownasilya** [comment]
In as of 1.2.0
